export const tokenRef = {
  'primary-primary-5': '#f8fcff',
  'primary-primary-10': '#d6eeff',
  'primary-primary-20': '#b2dfff',
  'primary-primary-30': '#82c8fa',
  'primary-primary-40': '#64b9f5',
  'primary-primary-50': '#1597f4',
  'primary-primary-60': '#158de2',
  'primary-primary-70': '#107ecc',
  'primary-primary-80': '#0f69a9',
  'primary-primary-90': '#064e82',
  'primary-primary-100': '#063b62',
  'blue-techblue-5': '#f8fcff',
  'blue-techblue-10': '#d6eeff',
  'blue-techblue-20': '#b2dfff',
  'blue-techblue-30': '#82c8fa',
  'blue-techblue-40': '#64b9f5',
  'blue-techblue-50': '#1597f4',
  'blue-techblue-60': '#158de2',
  'blue-techblue-70': '#107ecc',
  'blue-techblue-80': '#0f69a9',
  'blue-techblue-90': '#064e82',
  'blue-techblue-100': '#063b62',
  'neutral-white': '#ffffff',
  'neutral-gray-5': '#f8f6f6',
  'neutral-gray-10': '#e3e3e3',
  'neutral-gray-20': '#d5d5d5',
  'neutral-gray-30': '#bfbfbf',
  'neutral-gray-40': '#a7a7a7',
  'neutral-gray-50': '#878787',
  'neutral-gray-60': '#6f6f6f',
  'neutral-gray-70': '#656565',
  'neutral-gray-80': '#565656',
  'neutral-gray-90': '#464646',
  'neutral-gray-95': '#383838',
  'neutral-gray-100': '#1d1d1d',
  'red-red-5': '#fff7f4',
  'red-red-10': '#fed5cb',
  'red-red-20': '#ffb7a7',
  'red-red-30': '#fa866c',
  'red-red-40': '#f85631',
  'red-red-50': '#dc3812',
  'gold-gold-5': '#fef8ec',
  'gold-gold-10': '#fceac8',
  'gold-gold-20': '#f5d69a',
  'gold-gold-30': '#f2c773',
  'gold-gold-40': '#f3b438',
  'gold-gold-50': '#eca51c',
  'green-green-5': '#eefff0',
  'green-green-10': '#ceffd3',
  'green-green-20': '#8afe95',
  'green-green-30': '#2fe541',
  'green-green-40': '#1fc72f',
  'green-green-50': '#11a620',
  'purple-purple-5': '#f9f0ff',
  'purple-purple-10': '#efdbff',
  'purple-purple-20': '#d3adf7',
  'purple-purple-30': '#b37feb',
  'purple-purple-40': '#9254de',
  'purple-purple-50': '#7930d2',
  'cyan-cyan-5': '#f0feff',
  'cyan-cyan-10': '#c2f5f9',
  'cyan-cyan-20': '#93f3fb',
  'cyan-cyan-30': '#5feaf5',
  'cyan-cyan-40': '#37e4f2',
  'cyan-cyan-50': '#1edbea',
  'magenta-magenta-5': '#fff0f6',
  'magenta-magenta-10': '#ffd6e7',
  'magenta-magenta-20': '#ffadd2',
  'magenta-magenta-30': '#ff85c0',
  'magenta-magenta-40': '#f759ab',
  'magenta-magenta-50': '#dd2f89',
  'family-family': 'SF Pro Display',
  'weight-regular': 'Regular',
  'weight-medium': 'Medium',
  'weight-semibold': 'Semi Bold',
  'weight-bold': 'Bold',
  'weight-light': 'Light',
  'weight-italic-regular': 'Regular italic',
  'weight-italic-bold': 'Bold Italic',
  'size-small': 12,
  'size-base': 14,
  'size-large': 16,
  'size-xlarge': 20,
  'size-heading1': 40,
  'size-heading2': 32,
  'size-heading3': 28,
  'size-heading4': 24,
  'size-heading5': 20,
  'size-heading6': 16,
  'lineheight-lineheight-sm': 16,
  'lineheight-lineheight-base': 20,
  'lineheight-lineheight-lg': 22,
  'lineheight-lineheight-xl': 28,
  'lineheight-lineheight-h6': 22,
  'lineheight-lineheight-h5': 26,
  'lineheight-lineheight-h4': 32,
  'lineheight-lineheight-h3': 36,
  'lineheight-lineheight-h2': 40,
  'lineheight-lineheight-h1': 48,
  'text-text-white': '#ffffff',
  'text-text-neutral-10': '#bfbfbf',
  'text-text-neutral-20': '#878787',
  'text-text-neutral-30': '#656565',
  'text-text-neutral-40': '#464646',
  'text-text-neutral-50': '#1d1d1d',
  'text-text-primary-10': '#82c8fa',
  'text-text-primary-20': '#1597f4',
  'text-text-primary-30': '#158de2',
  'text-text-disabled': '#bfbfbf',
  'text-text-placeholder': '#a7a7a7',
  'text-text-red': '#dc3812',
  'text-text-green': '#11a620',
  'border-border-white': '#ffffff',
  'border-border-neutral-10': '#f8f6f6',
  'border-border-neutral-20': '#e3e3e3',
  'border-border-neutral-30': '#d5d5d5',
  'border-border-neutral-40': '#bfbfbf',
  'border-border-neutral-50': '#6f6f6f',
  'border-border-neutral-60': '#464646',
  'border-border-primary-10': '#64b9f5',
  'border-border-primary-20': '#158de2',
  'border-border-primary-30': '#107ecc',
  'border-border-red-10': '#fa866c',
  'border-border-red-20': '#dc3812',
  'border-border-green-10': '#2fe541',
  'border-border-green-20': '#11a620',
  'border-border-purple-10': '#b37feb',
  'border-border-purple-20': '#7930d2',
  'border-border-disabled': '#d5d5d5',
  'border-border-focused-primary': '#82c8fa',
  'border-radius-small': 4,
  'border-radius-base': 8,
  'border-radius-large': 12,
  'border-radius-large2x': 16,
  'border-radius-large3x': 24,
  'border-radius-rounded': 999,
  'background-bg-app': '#f8f8fb',
  'background-bg-white': '#ffffff',
  'background-bg-white-hover': '#f8f6f6',
  'background-bg-neutral-5': '#f8f6f6',
  'background-bg-neutral-10': '#e3e3e3',
  'background-bg-neutral-20': '#d5d5d5',
  'background-bg-primary': '#1597f4',
  'background-bg-primary-hover': '#158de2',
  'background-bg-red': '#f85631',
  'background-bg-red-hover': '#dc3812',
  'background-bg-green': '#1fc72f',
  'background-bg-green-hover': '#11a620',
  'background-bg-disabled': '#f8f6f6',



  'spacing-sm': '12',
  'spacing-3x': '12',
  'brands-black': '000',
  'corner-radius-0': '0',
  'primary-primary-0,5': '#eaeff8',
  'primary-primary-1': '#d5e0f2',
  'primary-primary-2': '#abc1e4',
  'primary-primary-3': '#81a2d7',
  'primary-primary-4': '#5783c9',
  'primary-primary-6': '#245096',
  'primary-primary-7': '#1b3c71',
  'primary-primary-8': '#12284b',
  'primary-primary-9': '#0e1e38',
  'tech blue-techblue-0,5': '#eaeff8',
  'tech blue-techblue-1': '#d5e0f2',
  'tech blue-techblue-2': '#abc1e4',
  'tech blue-techblue-3': '#81a2d7',
  'tech blue-techblue-4': '#5783c9',
  'tech blue-techblue-5': '#2d64bc',
  'tech blue-techblue-6': '#245096',
  'tech blue-techblue-7': '#1b3c71',
  'tech blue-techblue-8': '#12284b',
  'tech blue-techblue-9': '#0e1e38',
  'tech blue-techblue-10': '#091426',
  'dust red-red-0,5': '#fff0ec',
  'dust red-red-1': '#ffe0d9',
  'dust red-red-2': '#ffc1b3',
  'dust red-red-3': '#ffa38e',
  'dust red-red-4': '#ff8468',
  'dust red-red-5': '#ff6542',
  'dust red-red-6': '#cc5135',
  'dust red-red-7': '#993d28',
  'dust red-red-8': '#66281a',
  'dust red-red-9': '#4d1e14',
  'dust red-red-10': '#33140d',
  'calendula gold-gold-0,5': '#fef5ec',
  'calendula gold-gold-1': '#ffe5c7',
  'calendula gold-gold-2': '#fdd9b3',
  'calendula gold-gold-3': '#fcc58e',
  'calendula gold-gold-4': '#fbb268',
  'calendula gold-gold-5': '#fa9f42',
  'calendula gold-gold-6': '#cc8135',
  'calendula gold-gold-7': '#9e6328',
  'calendula gold-gold-8': '#70461b',
  'calendula gold-gold-9': '#42280e',
  'calendula gold-gold-10': '#2b1908',
  'polar green-green-0,5': '#f7fde8',
  'polar green-green-1': '#ecf6d2',
  'polar green-green-2': '#dae9b0',
  'polar green-green-3': '#b9d56c',
  'polar green-green-4': '#a3c73e',
  'polar green-green-5': '#8db911',
  'polar green-green-6': '#71940e',
  'polar green-green-7': '#556f0a',
  'polar green-green-8': '#384a07',
  'polar green-green-9': '#2a3805',
  'polar green-green-10': '#1c2503',
  'neutral-gray-1': '#f8f6f6',
  'neutral-gray-2': '#e3e3e3',
  'neutral-gray-3': '#d5d5d5',
  'neutral-gray-4': '#c7c7c7',
  'neutral-gray-6': '#8f8f8f',
  'neutral-gray-7': '#737373',
  'neutral-gray-8': '#5c5c5c',
  'neutral-gray-9': '#454545',
  'neutral-gray-11': '#232323',
  'neutral-gray-12': '#171717',
  'neutral-gray-13': '#0c0c0c',
  'lime-lime-1': '#fcffe6',
  'lime-lime-2': '#f4ffb8',
  'lime-lime-3': '#eaff8f',
  'lime-lime-4': '#d3f261',
  'lime-lime-5': '#bae637',
  'lime-lime-6': '#a0d911',
  'lime-lime-7': '#7cb305',
  'lime-lime-8': '#5b8c00',
  'lime-lime-9': '#3f6600',
  'lime-lime-10': '#254000',
  'cyan-cyan-1': '#e6fffb',
  'cyan-cyan-2': '#b5f5ec',
  'cyan-cyan-3': '#87e8de',
  'cyan-cyan-4': '#5cdbd3',
  'cyan-cyan-6': '#13c2c2',
  'cyan-cyan-7': '#08979c',
  'cyan-cyan-8': '#006d75',
  'cyan-cyan-9': '#00474f',
  'golden purple-purple-1': '#f9f0ff',
  'golden purple-purple-2': '#efdbff',
  'golden purple-purple-3': '#d3adf7',
  'golden purple-purple-4': '#b37feb',
  'golden purple-purple-5': '#9254de',
  'golden purple-purple-6': '#722ed1',
  'golden purple-purple-7': '#531dab',
  'golden purple-purple-8': '#391085',
  'golden purple-purple-9': '#22075e',
  'golden purple-purple-10': '#120338',
  'magenta-magenta-1': '#fff0f6',
  'magenta-magenta-2': '#ffd6e7',
  'magenta-magenta-3': '#ffadd2',
  'magenta-magenta-4': '#ff85c0',
  'magenta-magenta-6': '#eb2f96',
  'magenta-magenta-7': '#c41d7f',
  'magenta-magenta-8': '#9e1068',
  'magenta-magenta-9': '#780650',
  'opacity-black-black-opacity-100': '#000000',
  'opacity-black-black-opacity-88': 'rgba(0, 0, 0, .88)',
  'opacity-black-black-opacity-65': 'rgba(0, 0, 0, .65)',
  'opacity-black-black-opacity-45': 'rgba(0, 0, 0, .45)',
  'opacity-black-black-opacity-25': 'rgba(0, 0, 0, .25)',
  'opacity-black-black-opacity-15': 'rgba(0, 0, 0, .15)',
  'opacity-black-black-opacity-6': 'rgba(0, 0, 0, .06)',
  'opacity-black-black-opacity-4': 'rgba(0, 0, 0, .04)',
  'opacity-black-black-opacity-2': 'rgba(0, 0, 0, .02)',
  'opacity-white-white-opacity-100': '#ffffff',
  'opacity-white-white-opacity-88': 'rgba(255, 255, 255, .88)',
  'opacity-white-white-opacity-65': 'rgba(255, 255, 255, .65)',
  'opacity-white-white-opacity-45': 'rgba(255, 255, 255, .45)',
  'opacity-white-white-opacity-25': 'rgba(255, 255, 255, .25)',
  'opacity-white-white-opacity-15': 'rgba(255, 255, 255, .15)',
  'opacity-white-white-opacity-6': 'rgba(255, 255, 255, .06)',
  'opacity-white-white-opacity-4': 'rgba(255, 255, 255, .04)',
  'opacity-white-white-opacity-2': 'rgba(255, 255, 255, .02)',
  'color-primary-colorprimarybg': '#eaeff8',
  'color-primary-colorprimarybghover': '#abc1e4',
  'color-primary-colorprimaryborder': '#abc1e4',
  'color-primary-colorprimaryborderhover': '#d5e0f2',
  'color-primary-colorprimaryhover': '#5783c9',
  'color-primary-colorprimary': '#2d64bc',
  'color-primary-colorprimaryactive': '#2d64bc',
  'color-primary-colorprimarytexthover': '#5783c9',
  'color-primary-colorprimarytext': '#2d64bc',
  'color-primary-colorprimarytextactive': '#2d64bc',
  'color-primary-colorlinkactive': '#2d64bc',
  'color-primary-colorlinkhover': '#81a2d7',
  'color-neutral-background-colorbgcontainer': '#ffffff',
  'color-neutral-background-colorbgelevated': '#f8f6f6',
  'color-neutral-background-colorbglayout': '#e3e3e3',
  'color-neutral-background-colorbgspotlight': 'rgba(0, 0, 0, .88)',
  'color-neutral-background-colorbgmask': 'rgba(0, 0, 0, .45)',
  'color-neutral-background-colorbgcontainerdisabled': 'rgba(0, 0, 0, .04)',
  'color-neutral-background-controlitembghover': 'rgba(0, 0, 0, .04)',
  'color-neutral-background-controlitembgactive': '#eaeff8',
  'color-neutral-background-controlitembgactivehover': '#d5e0f2',
  'color-neutral-background-controlitembgactivedisabled': 'rgba(0, 0, 0, .15)',
  'color-neutral-background-colorbgtextactive': 'rgba(0, 0, 0, .15)',
  'color-neutral-background-colorbgtexthover': 'rgba(0, 0, 0, .06)',
  'color-neutral-fill-colorfill': 'rgba(0, 0, 0, .15)',
  'color-neutral-fill-colorfillsecondary': 'rgba(0, 0, 0, 0.06)',
  'color-neutral-fill-colorfilltertiary': 'rgba(0, 0, 0, .04)',
  'color-neutral-fill-colorfillquaternary': 'rgba(0, 0, 0, .02)',
  'color-neutral-fill-colorwhitefill': 'rgba(255, 255, 255, .15)',
  'color-neutral-fill-colorwhitesecondary': 'rgba(255, 255, 255, .06)',
  'color-neutral-fill-colorwhitetertiary': 'rgba(255, 255, 255, .04)',
  'color-neutral-fill-colorwhitequaternary': 'rgba(255, 255, 255, .02)',
  'color-neutral-text-colortext': 'rgba(0, 0, 0, .88)',
  'color-neutral-text-colortextlabel': 'rgba(0, 0, 0, .65)',
  'color-neutral-text-colortextdescription': 'rgba(0, 0, 0, .45)',
  'color-neutral-text-colortextplaceholder': 'rgba(0, 0, 0, .25)',
  'color-neutral-text-colortextdisabled': 'rgba(0, 0, 0, .25)',
  'color-neutral-text-coloricon': 'rgba(0, 0, 0, .45)',
  'color-neutral-text-coloriconhover': 'rgba(0, 0, 0, .88)',
  'color-neutral-text-colortextsolid': '#ffffff',
  'color-neutral-borders-colorborder': 'rgba(0, 0, 0, .15)',
  'color-neutral-borders-colorbordersecondary': 'rgba(0, 0, 0, .25)',
  'color-neutral-borders-colorsplit': 'rgba(0, 0, 0, .06)',
  'color-neutral-borders-colorwhiteborder': 'rgba(255, 255, 255, .15)',
  'color-neutral-borders-colorwhitebordersecondary': 'rgba(255, 255, 255, .25)',
  'color-neutral-borders-colorwhitesplit': 'rgba(255, 255, 255, .06)',
  'color-success-colorsuccessbg': '#f7fde8',
  'color-success-colorsuccessbghover': '#dae9b0',
  'color-success-colorsuccessborder': '#dae9b0',
  'color-success-colorsuccessborderhover': '#ecf6d2',
  'color-success-colorsuccesshover': '#a3c73e',
  'color-success-colorsuccess': '#8db911',
  'color-success-colorsuccessactive': '#8db911',
  'color-success-colorsuccesstexthover': '#a3c73e',
  'color-success-colorsuccesstext': '#8db911',
  'color-success-colorsuccesstextactive': '#8db911',
  'color-warning-colorwarningbg': '#fef5ec',
  'color-warning-colorwarningbghover': '#fdd9b3',
  'color-warning-colorwarningborder': '#fdd9b3',
  'color-warning-colorwarningborderhover': '#ffe5c7',
  'color-warning-colorwarninghover': '#fbb268',
  'color-warning-colorwarning': '#fa9f42',
  'color-warning-colorwarningactive': '#fa9f42',
  'color-warning-colorwarningtexthover': '#fbb268',
  'color-warning-colorwarningtext': '#fa9f42',
  'color-warning-colorwarningtextactive': '#fa9f42',
  'color-error-colorerrorbg': '#fff0ec',
  'color-error-colorerrorbghover': '#ffc1b3',
  'color-error-colorerrorborder': '#ffc1b3',
  'color-error-colorerrorborderhover': '#ffe0d9',
  'color-error-colorerrorhover': '#ff8468',
  'color-error-colorerror': '#ff6542',
  'color-error-colorerroractive': '#ff6542',
  'color-error-colorerrortexthover': '#ff8468',
  'color-error-colorerrortext': '#ff6542',
  'color-error-colorerrortextactive': '#ff6542',
  'color-info-colorinfobg': '#f8f6f6',
  'color-info-colorinfobghover': '#e3e3e3',
  'color-info-colorinfoborder': '#e3e3e3',
  'color-info-colorinfoborderhover': '#f8f6f6',
  'color-info-colorinfohover': '#737373',
  'color-info-colorinfo': '#2e2e2e',
  'color-info-colorinfoactive': '#2e2e2e',
  'color-info-colorinfotexthover': 'rgba(0, 0, 0, .65)',
  'color-info-colorinfotext': 'rgba(0, 0, 0, .88)',
  'color-info-colorinfotextactive': 'rgba(0, 0, 0, .88)',
  'color-magneta-colormagentabg': '#fff0f6',
  'color-magneta-colormagentabghover': '#ffd6e7',
  'color-magneta-colormagentaborder': '#ffd6e7',
  'color-magneta-colormagentaborderhover': '#fff0f6',
  'color-magneta-colormagentahover': '#ff85c0',
  'color-magneta-colormagenta': '#f759ab',
  'color-magneta-colormagentaactive': '#f759ab',
  'color-magneta-colormagentatexthover': '#ff85c0',
  'color-magneta-colormagentatext': '#f759ab',
  'color-magneta-colormagentatextactive': '#f759ab',
  'color-gold purple-colorgoldpurplebg': '#f9f0ff',
  'color-gold purple-colorgoldpurplebghover': '#efdbff',
  'color-gold purple-colorgoldpurpleborder': '#efdbff',
  'color-gold purple-colorgoldpurpleborderhover': '#f9f0ff',
  'color-gold purple-colorgoldpurplehover': '#b37feb',
  'color-gold purple-colorgoldpurple': '#9254de',
  'color-gold purple-colorgoldpurpleactive': '#9254de',
  'color-gold purple-colorgoldpurpletexthover': '#b37feb',
  'color-gold purple-colorgoldpurpletext': '#9254de',
  'color-gold purple-colorgoldpurpletextactive': '#9254de',
  'color-cyan-colorcyanbg': '#e6fffb',
  'color-cyan-colorcyanbghover': '#b5f5ec',
  'color-cyan-colorcyanborder': '#b5f5ec',
  'color-cyan-colorcyanborderhover': '#e6fffb',
  'color-cyan-colorcyanhover': '#5cdbd3',
  'color-cyan-colorcyan': '#36cfc9',
  'color-cyan-colorcyanactive': '#36cfc9',
  'color-cyan-colorcyantexthover': '#5cdbd3',
  'color-cyan-colorcyantext': '#36cfc9',
  'color-cyan-colorcyantextactive': '#36cfc9',
  'color-polar green-colorpolarbg': '#ecf6d2',
  'color-polar green-colorpolarbghover': '#dae9b0',
  'color-polar green-colorpolarborder': '#dae9b0',
  'color-polar green-colorpolarborderhover': '#ecf6d2',
  'color-polar green-colorpolarhover': '#a3c73e',
  'color-polar green-colorpolar': '#8db911',
  'color-polar green-colorpolaractive': '#8db911',
  'color-polar green-colorpolartexthover': '#a3c73e',
  'color-polar green-colorpolartext': '#8db911',
  'color-polar green-colorpolartextactive': '#8db911',
  'color-lime-colorlimebg': '#f4ffb8',
  'color-lime-colorlimebghover': '#eaff8f',
  'color-lime-colorlimeborder': '#d3f261',
  'color-lime-colorlimeborderhover': '#eaff8f',
  'color-lime-colorlimehover': '#bae637',
  'color-lime-colorlime': '#a0d911',
  'color-lime-colorlimeactive': '#a0d911',
  'color-lime-colorlimetexthover': '#bae637',
  'color-lime-colorlimetext': '#7cb305',
  'color-lime-colorlimetextactive': '#a0d911',
  'color-calendual gold-colorgoldbg': '#ffe5c7',
  'color-calendual gold-colorgoldbghover': '#fdd9b3',
  'color-calendual gold-colorgoldborder': '#fdd9b3',
  'color-calendual gold-colorgoldborderhover': '#ffe5c7',
  'color-calendual gold-colorgoldhover': '#fbb268',
  'color-calendual gold-colorgold': '#fa9f42',
  'color-calendual gold-colorgoldactive': '#fa9f42',
  'color-calendual gold-colorgoldtexthover': '#fbb268',
  'color-calendual gold-colorgoldtext': '#fa9f42',
  'color-calendual gold-colorgoldtextactive': '#fa9f42',
  'color-gray-colorgraybg': '#f8f6f6',
  'color-gray-colorgraybghover': '#e3e3e3',
  'color-gray-colorgrayborder': '#e3e3e3',
  'color-gray-colorgrayborderhover': '#f8f6f6',
  'color-gray-colorgrayhover': '#c7c7c7',
  'color-gray-colorgray': '#ababab',
  'color-gray-colorgrayactive': '#171717',
  'color-gray-colorgraytexthover': '#2e2e2e',
  'color-gray-colorgraytext': '#171717',
  'color-gray-colorgraytextactive': '#171717',
  'size-size-sizemax-999px': 999,
  'size-size-size3xl-48px': 48,
  'size-size-size2xl-40px': 40,
  'size-size-sizexl-32px': 32,
  'size-size-sizelg-24px': 24,
  'size-size-sizemd-20px': 20,
  'size-size-size-16px': 16,
  'size-size-sizesm-12px': 12,
  'size-size-sizexs-8px': 8,
  'size-size-sizexxs-6px': 6,
  'size-size-sizexxxs-4px': 4,
  'size-size-size4xs-2px': 2,
  'size-size-size5xs-1px': 1,
  'size-size-size0-0px': 0,
  'size-padding-paddingxxl': 48,
  'size-padding-paddingxl': 32,
  'size-padding-paddinglg': 24,
  'size-padding-paddingmd': 20,
  'size-padding-padding': 16,
  'size-padding-paddingsm': 12,
  'size-padding-paddingxs': 8,
  'size-padding-paddingxxs': 4,
  'size-height-controlheightlg': 40,
  'size-height-controlheight': 32,
  'size-height-controlheightsm': 24,
  'size-height-controheightxs': 16,
  'size-screen-screenxxl': 1600,
  'size-screen-screenxxlmin': 1600,
  'size-screen-screenxl': 1200,
  'size-screen-screenxlmax': 1599,
  'size-screen-screenxlmin': 1200,
  'size-screen-screenlg': 992,
  'size-screen-screenlgmax': 1199,
  'size-screen-screenlgmin': 992,
  'size-screen-screenmd': 768,
  'size-screen-screenmdmax': 991,
  'size-screen-screenmdmin': 768,
  'size-screen-screensm': 576,
  'size-screen-screensmmax': 767,
  'size-screen-screensmmin': 576,
  'size-screen-screenxs': 480,
  'size-screen-screenxsmax': 575,
  'size-screen-screenxsmin': 480,
  'size-margin-marginxxl': 48,
  'size-margin-marginxl': 32,
  'size-margin-marginlg': 24,
  'size-margin-marginmd': 20,
  'size-margin-margin': 16,
  'size-margin-marginsm': 12,
  'size-margin-marginxs': 8,
  'size-margin-marginxxs': 4,
  'style-radius-borderradiuslg': 8,
  'style-radius-borderradiusxl': 16,
  'style-radius-borderradius2x': 20,
  'style-radius-borderradius3x': 24,
  'style-radius-borderradius': 8,
  'style-radius-borderradiussm': 6,
  'style-radius-borderradiusxs': 4,
  'style-radius-borderround': 999,
  'style-line-width-linewidth': 1,
  'style-line-width-linewidthbold': 2,
  'style-line-width-controloutlinewidth': 2,
  'style-line-width-linewidthfocus': 4,
  'font-family-fontfamily': "var(--sf-pro-display-font)",
  'font-family-fontfamilycode': "var--sf-pro-display-font)",
  'font-weight-regular': 'Regular',
  'font-weight-semibold': 'Semi Bold',
  'font-weight-bold': 'Bold',
  'font-weight-light': 'Light',
  'font-weight-italic-regular': 'Italic',
  'font-weight-italic-bold': 'Bold Italic',
  'font-size-fontsizesm': 12,
  'font-size-fontsize': 14,
  'font-size-fontsizelg': 16,
  'font-size-fontsizexl': 20,
  'font-size-fontsizeheading1': 40,
  'font-size-fontsizeheading2': 32,
  'font-size-fontsizeheading3': 28,
  'font-size-fontsizeheading4': 20,
  'font-size-fontsizeheading5': 16,
  'line-height-lineheightsm': 20,
  'line-height-lineheight': 22,
  'line-height-lineheightlg': 24,
  'line-height-lineheightxl': 28,
  'line-height-lineheightheading5': 24,
  'line-height-lineheightheading4': 28,
  'line-height-lineheightheading3': 32,
  'line-height-lineheightheading2': 38,
  'line-height-lineheightheading1': 46,
};